sudo: required
services:
  - docker

before_install:
  - docker build -t nabs2309/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nabs2309/react-test echo built

after_success:
  - docker build -t nabs2309/multi-client ./client
  - docker build -t nabs2309/multi-nginx ./nginx
  - docker build -t nabs2309/multi-server ./server
  - docker build -t nabs2309/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" docker login -u "$DOCKER_ID" --password-stdin
  - docker push nabs2309/multi-client
  - docker push nabs2309/multi-nginx
  - docker push nabs2309/multi-server
  - docker push nabs2309/multi-worker
